name: 'publish'

on:
  push:
    branches:
      - main
      - test/deployment

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    env:
      # point PyO3’s build-script at the copy you just downloaded/built
      PYO3_PYTHON: ${{ github.workspace }}/src-tauri/resources/py/${{ matrix.os }}/python3.12
    steps:
      - uses: actions/checkout@v4

      # ---- tooling --------------------------------------------------------
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - uses: actions/setup-java@v4           # antlr4-tools requires Java only at build time
        with:
          distribution: temurin
          java-version: '17'

      # ---- pip + PyInstaller ----------------------------------------------
      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Freeze sidecar with PyInstaller
        run: |
          pyinstaller -F src-python/__main__.py \
            --name paredros                      \
            --add-data "src-python${{ runner.os == 'Windows' && ';' || ':' }}." \
            --clean
          mkdir -p src-tauri/binaries
          cp dist/paredros{{ matrix.exe_ext }} \
            "src-tauri/binaries/paredros-py-${{ matrix.rust_target }}${{ matrix.exe_ext }}"

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
